def get_label_groups():
    return [
        {
            'id':0,
            'name':'Прочие признаки',
            'sort_index': 100,
        },
        {
            'id':1,
            'name':'Витреоретинальный и ретинальный интерфейс',
            'sort_index': 1,
        },
        {
            'id':2,
            'name':'Изменения контура сетчатки',
            'sort_index': 2,
        },
        {
            'id':3,
            'name':'Толщина сетчатки',
            'sort_index': 3,
        },
        {
            'id':4,
            'name':'Структура сетчатки',
            'sort_index': 4,
        },
        {
            'id':5,
            'name':'Хориоидея',
            'sort_index': 5,
        },
    ]


def get_label_markers():
    return {
        'koger_mak_square_1': {'name': 'Сетчатка в макулярной области без видимой патологии', 'sort_index': 1, 'type': 0},
        'koger_mak_square_2': {'name': 'Недостаточная прозрачность оптических сред для достоверной оценки изменений в структуре сетчатки', 'sort_index': 2, 'type': 0},
        'koger_mak_square_3': {'name': 'Сканирование затруднено вследствие отсутствия фиксации взора', 'sort_index': 3, 'type': 0},
        'koger_mak_square_4': {'name': 'Отмечается грубое нарушение архитектоники сетчатки', 'sort_index': 4, 'type': 0},
        'koger_mak_square_5': {'name': 'Слои сетчатки не дифференцируются', 'sort_index': 5, 'type': 0},

        'koger_mak_fovea_1': {'name': 'Наблюдается полная ЗОСТ', 'sort_index': 1, 'type': 1},
        'koger_mak_fovea_2': {'name': 'Наблюдается полная ЗОСТ с «крышечкой» (участок ткани сетчатки из фовеа)', 'sort_index': 2, 'type': 1},
        'koger_mak_fovea_3': {'name': 'Наблюдается неполная отслойка ЗГМ с адгезией в макуле', 'sort_index': 3, 'type': 1},
        'koger_mak_fovea_4': {'name': 'Наблюдается неполная отслойка ЗГМ с адгезией в фовеа', 'sort_index': 4, 'type': 1},
        'koger_mak_fovea_5': {'name': 'К сетчатке в макуле фиксированы тонкие нити', 'sort_index': 5, 'type': 1},
        'koger_mak_fovea_6': {'name': 'К сетчатке в макуле фиксированы шварты', 'sort_index': 6, 'type': 1},
        'koger_mak_fovea_7': {'name': 'К сетчатке в макуле фиксированы тонкие нити, тракционный синдром отсутствует', 'sort_index': 7, 'type': 1},
        'koger_mak_fovea_8': {'name': 'Наблюдается витреомакулярный тракционнный синдром (вертикальные тракции)', 'sort_index': 8, 'type': 1},
        'koger_mak_fovea_27': {'name': 'Наблюдается преретинальная мембрана', 'sort_index': 9, 'type': 1},
        'koger_mak_fovea_9': {'name': 'Наблюдается эпиретинальный фиброз', 'sort_index': 10, 'type': 1},
        'koger_mak_fovea_10': {'name': 'Наблюдается незначительный ЭРФ на периферии макулы (тракции отсутствуют)', 'sort_index': 11, 'type': 1},
        'koger_mak_fovea_11': {'name': 'Профиль сетчатки деформирован за счет тангенциальных горизонтальных тракций (фовеа сглажена)', 'sort_index': 12, 'type': 1},
        'koger_mak_fovea_12': {'name': 'Эпиретинальная мембрана частично отделилась самопроизвольно', 'sort_index': 13, 'type': 1},
        'koger_mak_fovea_13': {'name': 'Профиль сетчатки имеет волнообразную деформацию после пилинга', 'sort_index': 14, 'type': 1},
        'koger_mak_fovea_14': {'name': 'Наблюдаются остатки эпиретинальной мембраны на периферии макулы после пилинга', 'sort_index': 15, 'type': 1},
        'koger_mak_fovea_15': {'name': 'Определяется угроза макулярного разрыва', 'sort_index': 16, 'type': 1},
        'koger_mak_fovea_26': {'name': 'Определяется угроза макулярного разрыва за счет формирования крупных кист в фовеа и парафовеа', 'sort_index': 17, 'type': 1},
        'koger_mak_fovea_16': {'name': 'Определяется макулярный псевдоразрыв', 'sort_index': 18, 'type': 1},
        'koger_mak_fovea_17': {'name': 'Определяется  макулярный ламеллярный разрыв', 'sort_index': 19, 'type': 1},
        'koger_mak_fovea_18': {'name': 'Определяется макулярный разрыв II ст', 'sort_index': 20, 'type': 1},
        'koger_mak_fovea_19': {'name': 'Определяется макулярный разрыв III ст', 'sort_index': 21, 'type': 1},
        'koger_mak_fovea_20': {'name': 'Определяется макулярный разрыв IV ст', 'sort_index': 22, 'type': 1},
        'koger_mak_fovea_21': {'name': 'Наблюдается неполная отслойка ЗГМ с адгезией в парафовеа (d до 3 мм)', 'sort_index': 23, 'type': 1},
        'koger_mak_fovea_22': {'name': 'Наблюдается неполная отслойка ЗГМ с адгезией в парифовеа (d от 3 до 5 мм)', 'sort_index': 24, 'type': 1},
        'koger_mak_fovea_23': {'name': 'Наблюдается эпиретинальный фиброз в фовеа', 'sort_index': 25, 'type': 1},
        'koger_mak_fovea_24': {'name': 'Наблюдается эпиретинальный фиброз в парафовеа', 'sort_index': 26, 'type': 1},
        'koger_mak_fovea_25': {'name': 'Наблюдается эпиретинальный фиброз на переферии макулы', 'sort_index': 27, 'type': 1},

        'koger_mak_retina_1': {'name': 'Фовеа без изменений', 'sort_index': 1, 'type': 2},
        'koger_mak_retina_2': {'name': 'Фовеа сглажена', 'sort_index': 2, 'type': 2},
        'koger_mak_retina_3': {'name': 'Фовеа не дифференцируется по ОКТ', 'sort_index': 3, 'type': 2},
        'koger_mak_retina_4': {'name': 'Профиль макулы правильный', 'sort_index': 4, 'type': 2},
        'koger_mak_retina_5': {'name': 'Контур профиля макулярной зоны уплощен', 'sort_index': 5, 'type': 2},
        'koger_mak_retina_6': {'name': 'Контур профиля макулярной зоны деформирован', 'sort_index': 6, 'type': 2},
        'koger_mak_retina_7': {'name': 'Контур профиля макулярной зоны ассиметричный', 'sort_index': 7, 'type': 2},
        'koger_mak_retina_8': {'name': 'Наблюдается куполообразная макула', 'sort_index': 8, 'type': 2},
        'koger_mak_retina_9': {'name': 'Определяется депрессия слоев сетчатки и хориоидеи (последствия хориоретинита)', 'sort_index': 9, 'type': 2},

        'koger_mak_retina_10': {'name': 'Толщина в норме. Сегментация не нарушена', 'sort_index': 1, 'type': 3},
        'koger_mak_retina_11': {'name': 'Сетчатка в макуле по толщине ниже нормы', 'sort_index': 2, 'type': 3},
        'koger_mak_retina_12': {'name': 'Толщина ганглионарного комплекса в норме', 'sort_index': 3, 'type': 3},
        'koger_mak_retina_13': {'name': 'Толщина ганглионарного комплекса увеличена', 'sort_index': 4, 'type': 3},
        'koger_mak_retina_14': {'name': 'Толщина ганглионарного комплекса уменьшена', 'sort_index': 5, 'type': 3},
        'koger_mak_retina_15': {'name': 'Сетчатка в макуле утолщена умеренно (до 500 мкм)', 'sort_index': 6, 'type': 3},
        'koger_mak_retina_16': {'name': 'Сетчатка в макуле утолщена значительно (свыше 500 мкм)', 'sort_index': 7, 'type': 3},
        'koger_mak_retina_17': {'name': 'Внутренние слои сетчатки  равномерно утолщены, имеют повышенную рефлективность (ОКТ признаки острой ишемии)', 'sort_index': 8, 'type': 3},

        'koger_mak_retina_18': {'name': 'Определяется фокальный интраретинальный отек', 'sort_index': 1, 'type': 4},
        'koger_mak_retina_19': {'name': 'Определяется диффузный интраретинальный отек', 'sort_index': 2, 'type': 4},
        'koger_mak_retina_20': {'name': 'Определяется кистозный интраретинальный отек', 'sort_index': 3, 'type': 4},
        'koger_mak_retina_21': {'name': 'Изменения в виде мелких (до 50 мкм) единичных кист', 'sort_index': 4, 'type': 4},
        'koger_mak_retina_22': {'name': 'Изменения в виде средних (150-200 мкм) единичных кист', 'sort_index': 5, 'type': 4},
        'koger_mak_retina_23': {'name': 'Изменения в виде крупных (150-200 мкм) единичных кист', 'sort_index': 6, 'type': 4},
        'koger_mak_retina_24': {'name': 'Изменения в виде мелких (150-200 мкм) множественных кист', 'sort_index': 7, 'type': 4},
        'koger_mak_retina_25': {'name': 'Изменения в виде средних (150-200 мкм) множественных кист', 'sort_index': 8, 'type': 4},
        'koger_mak_retina_26': {'name': 'Изменения в виде крупных (150-200 мкм) множественных кист', 'sort_index': 9, 'type': 4},
        'koger_mak_retina_27': {'name': 'Определяется кистозная дегенерация сетчатки в макуле', 'sort_index': 10, 'type': 4},
        'koger_mak_retina_28': {'name': 'Сканируются интраретинальные полости неправильной формы с четкими контурами', 'sort_index': 11, 'type': 4},
        'koger_mak_retina_29': {'name': 'Сканируются интраретинальные щелеобразные полости', 'sort_index': 12, 'type': 4},
        'koger_mak_retina_30': {'name': 'Определяется ретиношизис наружных слоев сетчатки', 'sort_index': 13, 'type': 4},
        'koger_mak_retina_31': {'name': 'Определяется ретиношизис внутренних слоев сетчатки', 'sort_index': 14, 'type': 4},
        'koger_mak_retina_32': {'name': 'Сканируются гиперрефлективные фокусы в наружном плексиформном слое сетчатки (твердые экссудаты)', 'sort_index': 15, 'type': 4},
        'koger_mak_retina_33': {'name': 'Сканируются очаги округлой формы повышенной рефлективности с нечеткими контурами (мягкие экссудаты)', 'sort_index': 16, 'type': 4},
        'koger_mak_retina_34': {'name': 'Эллипсоидный слой фоторецепторов не изменен', 'sort_index': 17, 'type': 4},
        'koger_mak_retina_35': {'name': 'Эллипсоидный слой фоторецепторов истончен', 'sort_index': 18, 'type': 4},
        'koger_mak_retina_36': {'name': 'Эллипсоидный слой фоторецепторов частично разрушен', 'sort_index': 19, 'type': 4},
        'koger_mak_retina_37': {'name': 'Определяется отсутствие эллипсоидной зоны в центре макулы', 'sort_index': 20, 'type': 4},
        'koger_mak_retina_38': {'name': 'Определяется отсутствие эллипсоидной зоны в макуле за исключением области фовеа', 'sort_index': 21, 'type': 4},
        'koger_mak_retina_39': {'name': 'Определяется локальный дефект эллипсоидной зоны в проекции фовеа («солнечная» ретинопатия)', 'sort_index': 22, 'type': 4},
        'koger_mak_retina_40': {'name': 'Определяется широкий горизонтальный дефект(ы) эллипсоидной зоны прямоугольной формы в центре макулы', 'sort_index': 23, 'type': 4},
        'koger_mak_retina_77': {'name': 'Определяется множественные окончатые дефект(ы) эллипсоидной зоны (лазеркоагуляты)', 'sort_index': 24, 'type': 4},
        'koger_mak_retina_41': {'name': 'Определяется тубуляция фоторецепторов', 'sort_index': 25, 'type': 4},
        'koger_mak_retina_42': {'name': 'Определяется дезорганизация пигментного эпителия', 'sort_index': 26, 'type': 4},
        'koger_mak_retina_78': {'name': 'ПЭС сохранен', 'sort_index': 27, 'type': 4},
        'koger_mak_retina_79': {'name': 'Определяется атрофия слоя ПЭС (ГАС)', 'sort_index': 28, 'type': 4},
        'koger_mak_retina_80': {'name': 'ПЭС частично разрушен', 'sort_index': 29, 'type': 4},
        'koger_mak_retina_43': {'name': 'Сканируются друзы мелкие (<63 мкм) единичные', 'sort_index': 30, 'type': 4},
        'koger_mak_retina_44': {'name': 'Сканируются друзы мелкие (<63 мкм) множественные', 'sort_index': 31, 'type': 4},
        'koger_mak_retina_45': {'name': 'Сканируются друзы средние (63-124 мкм) единичные', 'sort_index': 32, 'type': 4},
        'koger_mak_retina_46': {'name': 'Сканируются друзы средние (63-124 мкм) множественные', 'sort_index': 33, 'type': 4},
        'koger_mak_retina_47': {'name': 'Сканируются друзы крупные (>125 мкм) единичные', 'sort_index': 34, 'type': 4},
        'koger_mak_retina_48': {'name': 'Сканируются друзы крупные (>125 мкм) множественные', 'sort_index': 35, 'type': 4},
        'koger_mak_retina_49': {'name': 'Сканируются друзы сливные', 'sort_index': 36, 'type': 4},
        'koger_mak_retina_50': {'name': 'Определяется друзеноидная отслойка ПЭС', 'sort_index': 37, 'type': 4},
        'koger_mak_retina_51': {'name': 'Сканируются ретикулярные(псевдодрузы)', 'sort_index': 38, 'type': 4},
        'koger_mak_retina_52': {'name': 'Сканируются кутикулярные друзы', 'sort_index': 39, 'type': 4},
        'koger_mak_retina_53': {'name': 'Сканируется серозная отслойка нейроэпителия', 'sort_index': 40, 'type': 4},
        'koger_mak_retina_81': {'name': 'Сканируется серозная щелевидная отслойка нейроэпителия', 'sort_index': 41, 'type': 4},
        'koger_mak_retina_54': {'name': 'Сканируется серозная отслойка пигментного эпителия сетчатки', 'sort_index': 42, 'type': 4},
        'koger_mak_retina_55': {'name': 'Отслойка ПЭС куполообразная', 'sort_index': 43, 'type': 4},
        'koger_mak_retina_56': {'name': 'Сканируется плоская волнообразная отслойка ПЭС', 'sort_index': 44, 'type': 4},
        'koger_mak_retina_82': {'name': 'Сканируется плоская отслойка ПЭС', 'sort_index': 45, 'type': 4},
        'koger_mak_retina_57': {'name': 'Сканируется table-образная отслойка ПЭС', 'sort_index': 46, 'type': 4},
        'koger_mak_retina_58': {'name': 'Сканируется геморрагическая отслойка ПЭ сетчатки', 'sort_index': 47, 'type': 4},
        'koger_mak_retina_59': {'name': 'Сканируется  фиброваскулярная отслойка ПЭ сетчатки', 'sort_index': 48, 'type': 4},
        'koger_mak_retina_86': {'name': 'Определяется симптом двойного слоя', 'sort_index': 49, 'type': 4},
        'koger_mak_retina_60': {'name': 'Помутнение высокой рефлективности, дающее "тень" на глубжележащие слои (субретинальное гемо)', 'sort_index': 50, 'type': 4},
        'koger_mak_retina_61': {'name': 'Сканируется субретинальная жидкость', 'sort_index': 51, 'type': 4},
        'koger_mak_retina_62': {'name': 'Сканируется субретинальный гиперрефлективный материал', 'sort_index': 52, 'type': 4},
        'koger_mak_retina_63': {'name': 'Сканируется разрыв в слое ПЭ сетчатки', 'sort_index': 53, 'type': 4},
        'koger_mak_retina_64': {'name': 'Сканируется гиперрефлективный очаг во внутренних слоях сетчатки', 'sort_index': 54, 'type': 4},
        'koger_mak_retina_65': {'name': 'Сканируется гиперрефлективный очаг в наружных слоях сетчатки', 'sort_index': 55, 'type': 4},
        'koger_mak_retina_66': {'name': 'Сканируется гиперрефлективный очаг над ПЭ', 'sort_index': 56, 'type': 4},
        'koger_mak_retina_67': {'name': 'Сканируется гиперрефлективный очаг в слое ПЭ', 'sort_index': 57, 'type': 4},
        'koger_mak_retina_68': {'name': 'Сканируется гиперрефлективный очаг под ПЭ', 'sort_index': 58, 'type': 4},
        'koger_mak_retina_69': {'name': 'Сканируется гиперрефлективный очаг, дающий "тень" на подлежащие слои', 'sort_index': 59, 'type': 4},
        'koger_mak_retina_70': {'name': 'Помутнение низкой рефлективности под отслойкой ПЭ сетчатки', 'sort_index': 60, 'type': 4},
        'koger_mak_retina_71': {'name': 'Помутнение высокой рефлективности под отслойкой ПЭ сетчатки', 'sort_index': 61, 'type': 4},
        'koger_mak_retina_72': {'name': 'Определяется дезорганизация внутренних слоев сетчатки (DRILL)', 'sort_index': 62, 'type': 4},
        'koger_mak_retina_73': {'name': 'Определяется ретиношизис на уровне наружнего плексиформного слоя', 'sort_index': 63, 'type': 4},
        'koger_mak_retina_74': {'name': 'Определяется ретиношизис на уровне внутрненнего ядерного слоя – множественные овальные вертикальные полости (ювенильный X- сцепленный ретиношизис)', 'sort_index': 64, 'type': 4},
        'koger_mak_retina_75': {'name': 'Определяется ретиношизис на уровне внутреннего плексиформного слоя', 'sort_index': 65, 'type': 4},
        'koger_mak_retina_76': {'name': 'Определяется ретиношизис сетчатки – миопический внутренний ретиношизис', 'sort_index': 66, 'type': 4},
        'koger_mak_retina_84': {'name': 'Сканируются гипорефлективные интраретинальные округлые полости с гиперрефлективными стенками (микроаневризмы)', 'sort_index': 67, 'type': 4},

        'koger_mak_neurodetach_1': {'name': 'Хориоидея обычной толщины, хорошо сегментированы слои хориоидальных сосудов', 'sort_index': 1, 'type': 5},
        'koger_mak_neurodetach_2': {'name': 'Хориоидея истончена  и атрофично изменена', 'sort_index': 2, 'type': 5},
        'koger_mak_neurodetach_3': {'name': 'Определяется хориосклероз', 'sort_index': 3, 'type': 5},
        'koger_mak_neurodetach_4': {'name': 'Участок усиления рефлективности в слое хориокапиляров', 'sort_index': 4, 'type': 5},
        'koger_mak_neurodetach_5': {'name': 'Хориоидеа утолщена в проекции макулы', 'sort_index': 5, 'type': 5},
        'koger_mak_neurodetach_6': {'name': 'В слое хориокапилляров определяется гиперрефлективный участок в виде щирокой полосы – пигментный невус', 'sort_index': 6, 'type': 5},
        'koger_mak_neurodetach_7': {'name': 'Определяется обширное гипорефлективное пространство в слое хориоидеа около ДЗН (полость кавитации при высокой миопии)', 'sort_index': 7, 'type': 5}
    }

def get_additional_props():
    return [
        {'id': 1, 'name': 'Субретинальная жидкость', 'count': 5},
        {'id': 2, 'name': 'Интраретинальные кисты', 'count': 9},
        {'id': 3, 'name': 'Отслойка ретинального пигментного эпителия', 'count': 9},
        {'id': 4, 'name': 'Субретинальный гиперрефлективный материал', 'count': 3},
        {'id': 5, 'name': 'Эпиретинальная мембрана', 'count': 7},
        {'id': 6, 'name': 'Ретинальные друзы', 'count': 9},
        {'id': 7, 'name': 'Сквозной макулярный разрыв', 'count': 3},
        {'id': 8, 'name': 'Ламеллярный макулярный разрыв', 'count': 3},
        {'id': 9, 'name': 'Витреомакулярная тракция', 'count': 6},
        {'id': 10, 'name': 'Диабетическая ретинопатия', 'count': 13},
        {'id': 11, 'name': 'Невус', 'count': 2},
        {'id': 12, 'name': 'Центральная серозная хориоретинопатия', 'count': 6},
        {'id': 13, 'name': 'ВМД, сухая форма', 'count': 9},
        {'id': 14, 'name': 'ВМД, экссудативная форма', 'count': 19},
        {'id': 15, 'name': 'Солнечная ретинопатия', 'count': 2},
        {'id': 16, 'name': 'Миопия высокой степени', 'count': 11},
        {'id': 17, 'name': 'Ретинальные кровоизлияния', 'count': 5},
        {'id': 18, 'name': 'Отслойка сетчатки', 'count': 3},
        {'id': 19, 'name': 'Нарушения кровообращения (тромбоз ЦВС или окклюзия ЦАС)', 'count': 13},
        {'id': 20, 'name': 'Кистозный макулярный отек (Ирвин-Гасса)', 'count': 4},
        {'id': 21, 'name': 'Скрытая субретинальная неоваскулярная мембрана', 'count': 4},
        {'id': 22, 'name': 'Географическая атрофия сетчатки', 'count': 6},
        {'id': 23, 'name': 'Стафиломы', 'count': 6},
        {'id': 24, 'name': 'Хориоретинальные рубцы', 'count': 6},
        {'id': 25, 'name': 'Ретиношизис', 'count': 8}
    ]

def get_map_addition_props():
    return {
        "1": [
            "koger_mak_retina_15",
            "koger_mak_retina_16",
            "koger_mak_retina_53",
            "koger_mak_retina_81",
            "koger_mak_retina_61"
        ],
        "2": [
            "koger_mak_retina_15",
            "koger_mak_retina_16",
            "koger_mak_retina_20",
            "koger_mak_retina_21",
            "koger_mak_retina_22",
            "koger_mak_retina_23",
            "koger_mak_retina_24",
            "koger_mak_retina_25",
            "koger_mak_retina_26"
        ],
        "3": [
            "koger_mak_retina_15",
            "koger_mak_retina_16",
            "koger_mak_retina_54",
            "koger_mak_retina_55",
            "koger_mak_retina_56",
            "koger_mak_retina_82",
            "koger_mak_retina_57",
            "koger_mak_retina_58",
            "koger_mak_retina_59"
        ],
        "4": [
            "koger_mak_retina_62",
            "koger_mak_retina_70",
            "koger_mak_retina_71"
        ],
        "5": [
            "koger_mak_fovea_9",
            "koger_mak_fovea_10",
            "koger_mak_fovea_11",
            "koger_mak_fovea_12",
            "koger_mak_retina_2",
            "koger_mak_retina_15",
            "koger_mak_retina_16"
        ],
        "6": [
            "koger_mak_retina_43",
            "koger_mak_retina_44",
            "koger_mak_retina_45",
            "koger_mak_retina_46",
            "koger_mak_retina_47",
            "koger_mak_retina_48",
            "koger_mak_retina_49",
            "koger_mak_retina_51",
            "koger_mak_retina_52"
        ],
        "7": [
            "koger_mak_fovea_18",
            "koger_mak_fovea_19",
            "koger_mak_fovea_20"
        ],
        "8": [
            "koger_mak_fovea_26",
            "koger_mak_fovea_16",
            "koger_mak_fovea_17"
        ],
        "9": [
            "koger_mak_fovea_3",
            "koger_mak_fovea_4",
            "koger_mak_fovea_5",
            "koger_mak_fovea_6",
            "koger_mak_fovea_7",
            "koger_mak_fovea_8"
        ],
        "10": [
            "koger_mak_fovea_6",
            "koger_mak_fovea_8",
            "koger_mak_retina_15",
            "koger_mak_retina_16",
            "koger_mak_retina_18",
            "koger_mak_retina_19",
            "koger_mak_retina_20",
            "koger_mak_retina_32",
            "koger_mak_retina_33",
            "koger_mak_retina_77",
            "koger_mak_retina_81",
            "koger_mak_retina_72",
            "koger_mak_retina_84"
        ],
        "11": [
            "koger_mak_neurodetach_4",
            "koger_mak_neurodetach_6"
        ],
        "12": [
            "koger_mak_retina_15",
            "koger_mak_retina_16",
            "koger_mak_retina_53",
            "koger_mak_retina_81",
            "koger_mak_retina_54",
            "koger_mak_retina_82"
        ],
        "13": [
            "koger_mak_retina_43",
            "koger_mak_retina_44",
            "koger_mak_retina_45",
            "koger_mak_retina_46",
            "koger_mak_retina_47",
            "koger_mak_retina_48",
            "koger_mak_retina_49",
            "koger_mak_retina_51",
            "koger_mak_retina_52"
        ],
        "14": [
            "koger_mak_retina_15",
            "koger_mak_retina_16",
            "koger_mak_retina_20",
            "koger_mak_retina_50",
            "koger_mak_retina_53",
            "koger_mak_retina_81",
            "koger_mak_retina_54",
            "koger_mak_retina_55",
            "koger_mak_retina_56",
            "koger_mak_retina_82",
            "koger_mak_retina_57",
            "koger_mak_retina_58",
            "koger_mak_retina_59",
            "koger_mak_retina_86",
            "koger_mak_retina_61",
            "koger_mak_retina_66",
            "koger_mak_retina_67",
            "koger_mak_retina_68",
            "koger_mak_retina_69"
        ],
        "15": [
            "koger_mak_retina_37",
            "koger_mak_retina_39"
        ],
        "16": [
            "koger_mak_retina_8",
            "koger_mak_retina_11",
            "koger_mak_retina_35",
            "koger_mak_retina_36",
            "koger_mak_retina_80",
            "koger_mak_retina_67",
            "koger_mak_retina_68",
            "koger_mak_retina_76",
            "koger_mak_neurodetach_2",
            "koger_mak_neurodetach_3",
            "koger_mak_neurodetach_7"
        ],
        "17": [
            "koger_mak_retina_15",
            "koger_mak_retina_16",
            "koger_mak_retina_58",
            "koger_mak_retina_60",
            "koger_mak_retina_71"
        ],
        "18": [
            "koger_mak_retina_15",
            "koger_mak_retina_16",
            "koger_mak_retina_53"
        ],
        "19": [
            "koger_mak_retina_15",
            "koger_mak_retina_16",
            "koger_mak_retina_17",
            "koger_mak_retina_18",
            "koger_mak_retina_19",
            "koger_mak_retina_20",
            "koger_mak_retina_21",
            "koger_mak_retina_22",
            "koger_mak_retina_23",
            "koger_mak_retina_24",
            "koger_mak_retina_25",
            "koger_mak_retina_26",
            "koger_mak_retina_32"
        ],
        "20": [
            "koger_mak_retina_16",
            "koger_mak_retina_20",
            "koger_mak_retina_53",
            "koger_mak_retina_81"
        ],
        "21": [
            "koger_mak_retina_15",
            "koger_mak_retina_54",
            "koger_mak_retina_56",
            "koger_mak_retina_82"
        ],
        "22": [
            "koger_mak_retina_5",
            "koger_mak_retina_11",
            "koger_mak_retina_79",
            "koger_mak_retina_80",
            "koger_mak_neurodetach_2",
            "koger_mak_neurodetach_3"
        ],
        "23": [
            "koger_mak_retina_35",
            "koger_mak_retina_36",
            "koger_mak_retina_80",
            "koger_mak_neurodetach_2",
            "koger_mak_neurodetach_3",
            "koger_mak_neurodetach_7"
        ],
        "24": [
            "koger_mak_retina_9",
            "koger_mak_retina_35",
            "koger_mak_retina_36",
            "koger_mak_retina_80",
            "koger_mak_neurodetach_2",
            "koger_mak_neurodetach_3"
        ],
        "25": [
            "koger_mak_retina_2",
            "koger_mak_retina_15",
            "koger_mak_retina_16",
            "koger_mak_retina_30",
            "koger_mak_retina_31",
            "koger_mak_retina_73",
            "koger_mak_retina_74",
            "koger_mak_retina_75"
        ]
    }