# Generated by Django 4.2.11 on 2024-04-03 17:22

from django.db import migrations

def load_retina_crop_types(apps, schema_editor):
    RetinaImageCropTypeOCT = apps.get_model("retinadeepai", "RetinaImageCropTypeOCT")
    retina_horizontal_type = RetinaImageCropTypeOCT(name='retina_horizontal', label='retina_horizontal', description='Горизонтальная проекция сетчатки', model_code=1)
    retina_horizontal_type.save()
    retina_vertical_type = RetinaImageCropTypeOCT(name='retina_vertical', label='retina_vertical', description='Вертикальная проекция сетчатки', model_code=2)
    retina_vertical_type.save()

def delete_retina_crop_types(apps, schema_editor):
    RetinaImageCropTypeOCT = apps.get_model("retinadeepai", "RetinaImageCropTypeOCT")
    RetinaImageCropTypeOCT.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('retinadeepai', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_retina_crop_types, delete_retina_crop_types),
    ]
