# Generated by Django 4.2.11 on 2024-04-03 17:28
from retinadeepai.markers import get_label_markers, get_label_groups
from django.db import migrations

def load_retina_groups(apps, schema_editor):
    RetinaLabelGroup = apps.get_model("retinadeepai", "RetinaLabelGroup")
    for group in get_label_groups():
        RetinaLabelGroup.objects.create(name=group['name'], sort_index=group['sort_index'])

def delete_retina_groups(apps, schema_editor):
    RetinaLabelGroup = apps.get_model("retinadeepai", "RetinaLabelGroup")
    RetinaLabelGroup.objects.all().delete()

def load_retina_label_marks(apps, schema_editor):
    RetinaLabelMark = apps.get_model("retinadeepai", "RetinaLabelMark")
    for label, info in get_label_markers().items():
        RetinaLabelMark.objects.create(label=label, group_id=info['type']+1, name=info['name'], sort_index=info['sort_index'])


def delete_retina_label_marks(apps, schema_editor):
    RetinaLabelMark = apps.get_model("retinadeepai", "RetinaLabelMark")
    RetinaLabelMark.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('retinadeepai', '0002_init_crop_type'),
    ]

    operations = [
        migrations.RunPython(load_retina_groups, reverse_code=delete_retina_groups),
        migrations.RunPython(load_retina_label_marks, reverse_code=delete_retina_label_marks),
    ]
