# Generated by Django 5.1.3 on 2024-11-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retinadeepai', '0003_fill_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='retinaimagecropoct',
            name='is_obb',
            field=models.BooleanField(default=False),
        ),
    ]
