# Generated by Django 5.1.3 on 2024-11-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retinadeepai', '0004_retinaimagecropoct_is_obb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retinaimagecropoct',
            name='is_obb',
        ),
        migrations.AddField(
            model_name='retinadetectiontask',
            name='is_obb',
            field=models.BooleanField(default=False),
        ),
    ]
