# Generated by Django 5.1.3 on 2024-12-06 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retinadeepai', '0005_remove_retinaimagecropoct_is_obb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retinaanalysisresult',
            name='is_corrected',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RetinaAnalysisCorrectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retinadeepai.retinalabelmark')),
                ('retina_analysis_crop_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retinadeepai.retinaanalysiscroptask')),
            ],
        ),
    ]
