# Generated by Django 5.1.3 on 2024-12-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retinadeepai', '0006_retinaanalysisresult_is_corrected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retinalabelmark',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
