# Generated by Django 5.1.3 on 2024-12-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retinadeepai', '0008_create_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retinaanalysiscorrectresult',
            old_name='label',
            new_name='label_mark',
        ),
        migrations.RemoveField(
            model_name='retinaanalysisresult',
            name='is_corrected',
        ),
        migrations.AddField(
            model_name='retinaanalysistask',
            name='is_corrected',
            field=models.BooleanField(default=False),
        ),
    ]
